[package]
name = "static-web-server"
version = "1.0.0-beta.1"
authors = ["Jose Quintana <https://git.io/joseluisq>"]
publish = false

[dependencies]
gotham = "0.4"
envy = "0.4"
serde = { version = "1.0", features = ["derive"] }

[profile.release]
lto = true
